// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconMdi:github': typeof import('~icons/mdi/github')['default']
    'IconUil:arrowDownRight': typeof import('~icons/uil/arrow-down-right')['default']
    'IconUil:arrowUpRight': typeof import('~icons/uil/arrow-up-right')['default']
    'IconUil:heart': typeof import('~icons/uil/heart')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
